### ISSUE TITLE
TwitchListConverter.cs in net35

### ISSUE THREAD

**Issue by lemoniscool** [gibletto/twitch.net#3]
Hi!
Im trying to use the file mentioned in the title in a different wrapper with net35 but i get the following error which i cant find a fix for:

2 - "System.Type" has no definition for "GetCustomAttribute" - TwitchListConverter.cs line 23

do you have any idea on how to fix it?
thanks in advance

**Comment by gibletto** [comment]
You probably figured this out, but try the non-generic version of the method.
